version: '3.8'

services:
  db: 
    container_name: grpc_db
    image: postgres:16.2
    restart: always
    ports:
      - 5432:5432
    env_file:
      - ./.env
    volumes:
      - app:/var/lib/postgresql/data

volumes:
  app: